-- Generated by Oracle SQL Developer REST Data Services 24.3.1.347.1826
-- Exported REST Definitions from ORDS Schema Version 23.1.0.r0861423
-- Schema: API_DEV_USER   Date: Wed Apr 01 10:52:06 IST 2026
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'API_DEV_USER',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'lms',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'activity_module',
      p_base_path      => '/activity/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'activity_module',
      p_pattern        => 'data',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'activity_module',
      p_pattern        => 'data',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
  l_card_id        NUMBER;
  l_card_exists    NUMBER;
  l_card_label     NVARCHAR2(500);
  l_card_sm_label  VARCHAR2(255);
  l_is_card_view   VARCHAR2(10);
  l_collapse_rest  VARCHAR2(10);
  l_activities     CLOB;
  l_final_json     CLOB;
  l_offset         NUMBER := 1;
  l_chunk_size     NUMBER := 32000;
  l_length         NUMBER;
  l_buffer         VARCHAR2(32767);
BEGIN
  -- [CORS HEADERS]
  OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
  HTP.P(''Access-Control-Allow-Origin: *'');
  HTP.P(''Access-Control-Allow-Methods: GET, POST, OPTIONS'');
  HTP.P(''Access-Control-Allow-Headers: Content-Type'');

  -- A. Validate ID
  BEGIN
      l_card_id := TO_NUMBER(:id);
  EXCEPTION WHEN OTHERS THEN
      HTP.P(''Content-Length: 26'');
      OWA_UTIL.HTTP_HEADER_CLOSE;
      HTP.PRN(''{"error": "Invalid ID"}'');
      RETURN;
  END;

  -- B. Fetch Card Details
  SELECT COUNT(*), MAX(LABEL), MAX(SM_LABEL), MAX(IS_CARD_VIEW), MAX(COLLAPSE_REST)
  INTO l_card_exists, l_card_label, l_card_sm_label, l_is_card_view, l_collapse_rest
  FROM CURRICULUM_CARDS
  WHERE ID = l_card_id;

  IF l_card_exists = 0 THEN
      HTP.P(''Content-Length: 30'');
      OWA_UTIL.HTTP_HEADER_CLOSE;
      HTP.PRN(''{"error": "Card not found"}'');
      RETURN;
  END IF;

  -- C. Fetch Activities and Group them by CHAPTER_NAME dynamically
  SELECT JSON_ARRAYAGG(
      JSON_OBJECT(
          ''type''     VALUE ''chapter'',
          ''label''    VALUE NVL(c.CHAPTER_NAME, l_card_label),
          ''id''       VALUE ''chap-'' || ROWNUM,
          ''desc''     VALUE c.CHAPTER_DESC,
          ''icon''     VALUE c.CHAPTER_ICON,
          ''style''    VALUE CASE WHEN c.CHAPTER_BG_COLOR IS NOT NULL 
                                THEN JSON_OBJECT(''backgroundColor'' VALUE c.CHAPTER_BG_COLOR) 
                                ELSE NULL END,
          ''list''     VALUE TREAT(c.ACT_LIST AS JSON)
          RETURNING CLOB
      ) ORDER BY c.MIN_ID ASC RETURNING CLOB
  )
  INTO l_activities
  FROM (
      SELECT 
          CHAPTER_NAME,
          MIN(a.ID) as MIN_ID, 
          MAX(CHAPTER_DESC) as CHAPTER_DESC,
          MAX(CHAPTER_ICON) as CHAPTER_ICON,
          MAX(CHAPTER_BG_COLOR) as CHAPTER_BG_COLOR,
          JSON_ARRAYAGG(
              JSON_OBJECT(
                  ''label''    VALUE a.LABEL,
                  ''id''       VALUE a.ID,
                  ''type''     VALUE a.ACTIVITY_TYPE,
                  ''btnLabel'' VALUE a.BTN_LABEL,
                  ''data''     VALUE COALESCE(JSON_QUERY(d.DATA_JSON, ''$'' RETURNING CLOB), JSON_OBJECT(RETURNING CLOB))
                  RETURNING CLOB
              ) ORDER BY a.ID ASC
              RETURNING CLOB
          ) AS ACT_LIST
      FROM ACTIVITIES a
      LEFT JOIN ACTIVITY_DATA d ON a.ID = d.ACTIVITY_ID
      WHERE a.CARD_ID = l_card_id
      GROUP BY CHAPTER_NAME
  ) c;

  IF l_activities IS NULL THEN l_activities := ''[]''; END IF;

  -- D. Construct Final JSON 
  SELECT JSON_SERIALIZE(
    JSON_OBJECT(
      ''label''        VALUE l_card_label,     
      ''altLabel''     VALUE l_card_sm_label,  
      ''id''           VALUE ''card-p'' || l_card_id,
      ''type''         VALUE ''nested'',
      ''cardView''     VALUE CASE WHEN NVL(l_is_card_view, ''false'') = ''true'' THEN ''true'' ELSE ''false'' END FORMAT JSON,
      ''collapseRest'' VALUE CASE WHEN NVL(l_collapse_rest, ''false'') = ''true'' THEN ''true'' ELSE ''false'' END FORMAT JSON,
      ''loadFirstAct'' VALUE CASE WHEN NVL(l_is_card_view, ''false'') = ''true'' THEN ''false'' ELSE ''true'' END FORMAT JSON,

      -- ADDING MISSING SUBCARDS STYLING
      ''iconStyle''    VALUE CASE WHEN NVL(l_is_card_view, ''false'') = ''true'' THEN JSON_OBJECT(''width'' VALUE 120, ''height'' VALUE 120) ELSE NULL END,
      ''cardStyle''    VALUE CASE WHEN NVL(l_is_card_view, ''false'') = ''true'' THEN JSON_OBJECT(''width'' VALUE 430, ''margin'' VALUE ''15px'', ''padding'' VALUE ''15px'', ''borderRadius'' VALUE 10, ''boxShadow'' VALUE ''var(--shadow)'', ''border'' VALUE ''1px solid #999'') ELSE NULL END,

      ''list''         VALUE TREAT(l_activities AS JSON) 
      RETURNING CLOB
    ) RETURNING CLOB
  ) INTO l_final_json FROM DUAL;

  -- E. SEND OUTPUT
  l_length := DBMS_LOB.GETLENGTH(l_final_json);
  HTP.P(''Content-Length: '' || l_length);
  OWA_UTIL.HTTP_HEADER_CLOSE;

  WHILE l_offset <= l_length LOOP
      DBMS_LOB.READ(l_final_json, l_chunk_size, l_offset, l_buffer);
      HTP.PRN(l_buffer);
      l_offset := l_offset + l_chunk_size;
  END LOOP;

EXCEPTION WHEN OTHERS THEN
  OWA_UTIL.HTTP_HEADER_CLOSE;
  HTP.PRN(''{"error": "'' || SQLERRM || ''"}'');
END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'auth_module',
      p_base_path      => '/auth/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'auth_module',
      p_pattern        => 'login',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'auth_module',
      p_pattern        => 'login',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
DECLARE
    l_name  VARCHAR2(100);
    l_email VARCHAR2(100);
    l_role  VARCHAR2(20);
    l_count NUMBER;
BEGIN
    SELECT count(*), MAX(admin_name), MAX(email), MAX(role)
      INTO l_count, l_name, l_email, l_role
      FROM lms_admins
     WHERE LOWER(email) = LOWER(:email)
       AND password_hash = RAWTOHEX(STANDARD_HASH(:password, ''SHA256''));

    IF l_count > 0 THEN
        UPDATE lms_admins SET last_login_at = SYSTIMESTAMP WHERE email = l_email;
        COMMIT;
        HTP.P(''{"status": "SUCCESS", "user": {"email": "''||l_email||''", "name": "''||l_name||''", "role": "''||l_role||''"}}'');
    ELSE
        OWA_UTIL.status_line(401);
        HTP.P(''{"status": "ERROR", "message": "Invalid credentials"}'');
    END IF;
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'auth_module',
      p_pattern        => 'profile',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'auth_module',
      p_pattern        => 'profile',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    UPDATE lms_admins 
       SET admin_name = :name 
     WHERE LOWER(email) = LOWER(:email);

    IF SQL%ROWCOUNT > 0 THEN
        COMMIT;
        HTP.P(''{"status": "SUCCESS", "message": "Admin name updated"}'');
    ELSE
        HTP.P(''{"status": "ERROR", "message": "User not found"}'');
    END IF;
END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'auth_module',
      p_pattern        => 'profile',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT admin_id as "id", admin_name as "name", email as "email", role as "role" 
                             FROM lms_admins 
                             WHERE LOWER(email) = LOWER(:email)'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'completedword_module',
      p_base_path      => '/completedword/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'completedword_module',
      p_pattern        => 'complete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'completedword_module',
      p_pattern        => 'complete',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        BEGIN
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            UPDATE completedword_attempts
            SET score = :score,
                attempted = :attempted,
                status = ''COMPLETED'',
                completed_at = SYSTIMESTAMP
            WHERE user_id = TO_NUMBER(:user_id)
              AND activity_id = :activity_id;

            COMMIT;
            HTP.P(''{"status":"success","message":"Activity Completed"}'');
        END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'completedword_module',
      p_pattern        => 'progress',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'completedword_module',
      p_pattern        => 'progress',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        BEGIN
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            MERGE INTO completedword_attempts t
            USING (
                SELECT TO_NUMBER(:user_id) AS src_uid, :activity_id AS src_aid FROM dual
            ) s
            ON (t.user_id = s.src_uid AND t.activity_id = s.src_aid)
            WHEN MATCHED THEN
                UPDATE SET
                    t.progress_json = :progress_json,
                    t.score = :score,
                    t.attempted = :attempted,
                    t.status = ''IN_PROGRESS'',
                    t.updated_at = SYSTIMESTAMP
            WHEN NOT MATCHED THEN
                INSERT (user_id, activity_id, progress_json, score, attempted, status, started_at)
                VALUES (s.src_uid, s.src_aid, :progress_json, :score, :attempted, ''IN_PROGRESS'', SYSTIMESTAMP);

            COMMIT;
            HTP.P(''{"status":"success"}'');
        END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'completedword_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'completedword_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        DECLARE
            v_json CLOB;
            v_status VARCHAR2(20);
        BEGIN
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            SELECT progress_json, status
            INTO v_json, v_status
            FROM completedword_attempts
            WHERE user_id = TO_NUMBER(:user_id)
              AND activity_id = :activity_id;

            -- Return the progress and status
            HTP.P(''{ "status": "'' || v_status || ''", "data": '' || NVL(v_json, ''null'') || '' }'');

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                HTP.P(''{"status":"empty"}'');
            WHEN OTHERS THEN
                HTP.P(''{"status":"error","message":"Server error"}'');
        END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'demo_module',
      p_base_path      => '/demo/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'My First API');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'demo_module',
      p_pattern        => 'employees',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo_module',
      p_pattern        => 'employees',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT emp_id, full_name, job_role, salary 
                             FROM employees 
                             ORDER BY emp_id'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'demo_module',
      p_pattern        => 'messages',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo_module',
      p_pattern        => 'messages',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                               -- Insert data using Bind Variables (matched to JSON keys)
                               INSERT INTO app_messages (sender, message_text)
                               VALUES (:sender, :message_text);

                               -- Output the new ID into the HTTP header (Standard practice)
                               :forward_location := ''demo/messages/'' || :msg_id;

                               -- Return HTTP 201 (Created) status
                               :status_code := 201; 

                               COMMIT;
                             END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo_module',
      p_pattern        => 'messages',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT msg_id, sender, message_text, created_at 
                             FROM app_messages 
                             ORDER BY msg_id DESC'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'demo_module',
      p_pattern        => 'messages/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo_module',
      p_pattern        => 'messages/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT msg_id, sender, message_text, created_at
                             FROM app_messages
                             WHERE msg_id = :id'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'demo_module',
      p_pattern        => 'time',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo_module',
      p_pattern        => 'time',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT ''Success! API is live.'' as message, 
                                    TO_CHAR(SYSDATE, ''HH24:MI:SS'') as current_time 
                             FROM DUAL'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'konzeptes_module',
      p_base_path      => '/kon/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'API for Curriculum Cards');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'konzeptes_module',
      p_pattern        => 'card',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'konzeptes_module',
      p_pattern        => 'card',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        BEGIN
            MERGE INTO CURRICULUM_CARDS c
            USING DUAL ON (c.id = :id)
            WHEN MATCHED THEN
                UPDATE SET c.label = :label, c.smLabel = :smLabel, c.img = :img
            WHEN NOT MATCHED THEN
                INSERT (id, label, smLabel, img)
                VALUES (:id, :label, :smLabel, :img);

            :status := 200;
        EXCEPTION
            WHEN OTHERS THEN
                :status := 500;
        END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'konzeptes_module',
      p_pattern            => 'card',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'konzeptes_module',
      p_pattern        => 'cards',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'konzeptes_module',
      p_pattern        => 'cards',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT id, label, smLabel "smLabel", img FROM CURRICULUM_CARDS ORDER BY id'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'lms_admin',
      p_base_path      => '/admin/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => 'LMS Admin APIs (Universal BLOB Fix)');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_admin',
      p_pattern        => 'delete/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_admin',
      p_pattern        => 'delete/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
      BEGIN
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        HTP.P(''Access-Control-Allow-Origin: *'');
        HTP.P(''Access-Control-Allow-Methods: DELETE, OPTIONS'');
        OWA_UTIL.HTTP_HEADER_CLOSE;

        DELETE FROM ACTIVITY_DATA WHERE activity_id = :id;
        DELETE FROM ACTIVITIES WHERE id = :id;
        HTP.P(''{"status":"success", "message":"Deleted"}'');
        COMMIT;
      EXCEPTION WHEN OTHERS THEN HTP.P(''{"error": "'' || SQLERRM || ''"}'');
      END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_admin',
      p_pattern        => 'list',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_admin',
      p_pattern        => 'list',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_first BOOLEAN := TRUE;
    l_chunk VARCHAR2(32767);
    l_offset NUMBER;
BEGIN
    -- 1. [CORS HEADERS]
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- 2. START JSON ARRAY
    HTP.PRN(''{"items": ['');

    -- 3. LOOP THROUGH EVERY ROW MANUALLY (Bypasses the 4000 char limit!)
    FOR r IN (
        SELECT a.id, a.card_id, a.label, a.activity_type, a.btn_label, d.data_json
        FROM ACTIVITIES a
        LEFT JOIN ACTIVITY_DATA d ON a.id = d.activity_id
    ) LOOP
        IF NOT l_first THEN
            HTP.PRN('','');
        END IF;
        l_first := FALSE;

        -- 4. PRINT JSON PROPERTIES
        HTP.PRN(''{"id": "'' || REPLACE(r.id, ''"'', ''\"'') || ''",'');
        HTP.PRN(''"card_id": "'' || NVL(TO_CHAR(r.card_id), '''') || ''",'');
        HTP.PRN(''"label": "'' || NVL(REPLACE(r.label, ''"'', ''\"''), '''') || ''",'');
        HTP.PRN(''"activity_type": "'' || NVL(r.activity_type, '''') || ''",'');
        HTP.PRN(''"btn_label": "'' || NVL(REPLACE(r.btn_label, ''"'', ''\"''), '''') || ''",'');

        HTP.PRN(''"data_json": '');

        -- 5. STREAM THE LARGE CLOB DIRECTLY
        IF r.data_json IS NOT NULL THEN
            l_offset := 1;
            WHILE l_offset <= DBMS_LOB.GETLENGTH(r.data_json) LOOP
                l_chunk := DBMS_LOB.SUBSTR(r.data_json, 8191, l_offset);
                HTP.PRN(l_chunk);
                l_offset := l_offset + 8191;
            END LOOP;
        ELSE
            HTP.PRN(''{}'');
        END IF;

        HTP.PRN(''}'');
    END LOOP;

    -- 6. END JSON ARRAY
    HTP.PRN('']}'');
EXCEPTION WHEN OTHERS THEN
    HTP.PRN(''{"error": "API Execution Error"}'');
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_admin',
      p_pattern        => 'save',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_admin',
      p_pattern        => 'save',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
      DECLARE
        l_blob        BLOB;
        l_body        CLOB;
        l_dest_offset INTEGER := 1;
        l_src_offset  INTEGER := 1;
        l_lang_context INTEGER := 0; -- DBMS_LOB.default_lang_ctx
        l_warning      INTEGER;

        l_act_id      VARCHAR2(100);
        l_card_id     NUMBER;
        l_label       VARCHAR2(500);
        l_type        VARCHAR2(100);
        l_btn_label   VARCHAR2(100);
        l_data_json   CLOB;
        l_new_id      VARCHAR2(100);
      BEGIN
        -- CORS HEADERS
        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        HTP.P(''Access-Control-Allow-Origin: *'');
        HTP.P(''Access-Control-Allow-Methods: POST, OPTIONS'');
        HTP.P(''Access-Control-Allow-Headers: Content-Type'');
        OWA_UTIL.HTTP_HEADER_CLOSE;

        -- FIX: Read the Implicit Bind Variable :body (BLOB)
        l_blob := :body;

        IF l_blob IS NULL OR DBMS_LOB.GETLENGTH(l_blob) = 0 THEN
           HTP.P(''{"status":"error", "message":"Empty Body"}'');
           RETURN;
        END IF;

        -- CONVERT BLOB TO CLOB (Safe for all DB versions)
        DBMS_LOB.CREATETEMPORARY(l_body, TRUE);
        DBMS_LOB.CONVERTTOCLOB(
             dest_lob     => l_body,
             src_blob     => l_blob,
             amount       => DBMS_LOB.LOBMAXSIZE,
             dest_offset  => l_dest_offset,
             src_offset   => l_src_offset,
             blob_csid    => 0, -- DBMS_LOB.default_csid
             lang_context => l_lang_context,
             warning      => l_warning
        );

        -- Extract Data using JSON_TABLE
        SELECT 
           jt.activity_id, jt.card_id, jt.label, jt.type_val, jt.btn_label, jt.data_json
        INTO 
           l_act_id, l_card_id, l_label, l_type, l_btn_label, l_data_json
        FROM JSON_TABLE(l_body, ''$''
           COLUMNS (
             activity_id  VARCHAR2(100) PATH ''$.activity_id'',
             card_id      NUMBER        PATH ''$.card_id'',
             label        VARCHAR2(500) PATH ''$.label'',
             type_val     VARCHAR2(100) PATH ''$.type'',
             btn_label    VARCHAR2(100) PATH ''$.btn_label'',
             data_json    CLOB          PATH ''$.data_json''
           )
        ) jt;

        -- INSERT OR UPDATE
        IF l_act_id IS NULL OR l_act_id = '''' THEN
           l_new_id := ''act-'' || TO_CHAR(SYSTIMESTAMP, ''YYYYMMDDHH24MISSFF3'');

           INSERT INTO ACTIVITIES (id, card_id, label, activity_type, btn_label)
           VALUES (l_new_id, l_card_id, l_label, l_type, l_btn_label);

           INSERT INTO ACTIVITY_DATA (activity_id, data_json)
           VALUES (l_new_id, l_data_json);

           HTP.P(''{"status":"success", "action":"inserted", "id":"'' || l_new_id || ''"}'');
        ELSE
           UPDATE ACTIVITIES 
           SET card_id = l_card_id, label = l_label, activity_type = l_type, btn_label = l_btn_label
           WHERE id = l_act_id;

           MERGE INTO ACTIVITY_DATA d
           USING (SELECT l_act_id as aid, l_data_json as djson FROM DUAL) s
           ON (d.activity_id = s.aid)
           WHEN MATCHED THEN UPDATE SET d.data_json = s.djson
           WHEN NOT MATCHED THEN INSERT (activity_id, data_json) VALUES (s.aid, s.djson);

           HTP.P(''{"status":"success", "action":"updated"}'');
        END IF;

        COMMIT;
        DBMS_LOB.FREETEMPORARY(l_body);

      EXCEPTION WHEN OTHERS THEN
        HTP.P(''{"status":"error", "message":"'' || SQLERRM || ''"}'');
        ROLLBACK;
      END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'lms_api',
      p_base_path      => '/v1/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => 'LMS User APIs');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_api',
      p_pattern        => 'users/all',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Fetch all records from lms_users');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_api',
      p_pattern        => 'users/all',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => 'Returns all user records',
      p_source         => 
'SELECT 
    user_id, 
    salutation, 
    TRIM(p_first_name || '' '' || p_last_name) AS parent_name, 
    TRIM(c_first_name || '' '' || c_last_name) AS child_name, 
    user_level, 
    mobile, 
    email, 
    created_at 
FROM lms_users 
ORDER BY created_at DESC'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_api',
      p_pattern        => 'users/latest',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Fetch latest registered users');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_api',
      p_pattern        => 'users/latest',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => 'Returns user list',
      p_source         => 
'SELECT 
    user_id, 
    salutation, 
    TRIM(p_first_name || '' '' || p_last_name) AS parent_name, 
    TRIM(c_first_name || '' '' || c_last_name) AS child_name, 
    user_level, 
    mobile, 
    email, 
    created_at 
FROM lms_users 
WHERE ROWNUM <= 10
ORDER BY created_at DESC'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'lms_module',
      p_base_path      => '/lms/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Module for User Dashboard Data');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_module',
      p_pattern        => 'v1/users/latest',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_module',
      p_pattern        => 'v1/users/latest',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        DECLARE
            v_first BOOLEAN := TRUE;
        BEGIN
            -- RESPONSE HEADERS (Crucial for fixing the CORS errors you saw)
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            HTP.P(''Access-Control-Allow-Methods: GET, POST, OPTIONS'');
            HTP.P(''Access-Control-Allow-Headers: Content-Type'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            -- START JSON CONSTRUCTION
            HTP.P(''{"items":['');

            -- FETCH LATEST USERS
            FOR r IN (
                SELECT 
                    user_id, 
                    salutation, 
                    INITCAP(parent_name) as parent_name, 
                    INITCAP(child_name) as child_name, 
                    LOWER(user_level) as user_level, 
                    mobile, 
                    email, 
                    TO_CHAR(created_at, ''YYYY-MM-DD"T"HH24:MI:SS"Z"'') as created_at
                FROM lms_users
                ORDER BY created_at DESC
                FETCH FIRST 10 ROWS ONLY
            ) LOOP
                IF NOT v_first THEN
                    HTP.P('','');
                END IF;

                HTP.P(
                    ''{'' ||
                    ''"user_id":''     || r.user_id     || '','' ||
                    ''"salutation":"''  || r.salutation  || ''",'' ||
                    ''"parent_name":"'' || r.parent_name || ''",'' ||
                    ''"child_name":"''  || r.child_name  || ''",'' ||
                    ''"user_level":"''  || r.user_level  || ''",'' ||
                    ''"mobile":"''      || r.mobile      || ''",'' ||
                    ''"email":"''       || r.email       || ''",'' ||
                    ''"created_at":"''   || r.created_at  || ''"'' ||
                    ''}''
                );
                v_first := FALSE;
            END LOOP;

            HTP.P('']} '');
        EXCEPTION
            WHEN OTHERS THEN
                HTP.P(''{"message":"Server Error: '' || SQLERRM || ''", "status":"error"}'');
        END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'lms_v2_user_api',
      p_base_path      => '/v2/user/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_v2_user_api',
      p_pattern        => 'login',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_v2_user_api',
      p_pattern        => 'login',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_user_id NUMBER;
    v_parent  VARCHAR2(200); -- Increased size for combined names
    v_child   VARCHAR2(200); -- Increased size for combined names
BEGIN
    -- 1. Set Headers
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- 2. Fetch data from the new columns
    -- We concatenate First and Last names with a space in between
    SELECT user_id, 
           (p_first_name || '' '' || p_last_name), 
           (c_first_name || '' '' || c_last_name)
      INTO v_user_id, v_parent, v_child
      FROM lms_users
     WHERE LOWER(email) = LOWER(:email)
       AND password_hash = STANDARD_HASH(:password, ''SHA256'');

    -- 3. Output JSON Response
    -- We use INITCAP to ensure the names look professional (e.g., "John Doe")
    HTP.P(''{'' ||
          ''"status":"success", '' ||
          ''"user_id":'' || v_user_id || '', '' ||
          ''"user":"'' || INITCAP(v_parent) || ''", '' ||
          ''"child_name":"'' || INITCAP(v_child) || ''", '' ||
          ''"message":"Login Success!"'' ||
          ''}'');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        -- Standard error for wrong email/password
        HTP.P(''{"status":"error", "message":"Invalid credentials"}'');
    WHEN OTHERS THEN
        -- Generic server error for debugging
        HTP.P(''{"status":"error", "message":"Server Error: '' || SQLERRM || ''"}'');
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'lms_v2_user_api',
      p_pattern        => 'register',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'lms_v2_user_api',
      p_pattern        => 'register',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_count NUMBER;
BEGIN
    -- 1. Standard Headers
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    -- 2. Check if Email already exists
    SELECT COUNT(*) INTO v_count FROM lms_users WHERE LOWER(email) = LOWER(:email);
    IF v_count > 0 THEN
        HTP.P(''{"status":"error", "message":"This Email Address is already registered!"}'');
        RETURN;
    END IF;

    -- 3. Check if Mobile already exists
    SELECT COUNT(*) INTO v_count FROM lms_users WHERE mobile = :mobile;
    IF v_count > 0 THEN
        HTP.P(''{"status":"error", "message":"This Mobile Number is already registered!"}'');
        RETURN;
    END IF;

    -- 4. If no duplicates, proceed with Insert
    INSERT INTO lms_users (
        salutation, 
        p_first_name, p_last_name, 
        c_first_name, c_last_name, 
        user_level, mobile, email, 
        password_hash,
        user_package
    )
    VALUES (
        :salutation, 
        :p_first_name, :p_last_name, 
        :c_first_name, :c_last_name, 
        :level, :mobile, :email, 
        STANDARD_HASH(:password, ''SHA256''),
        :package_type
    );

    COMMIT;
    HTP.P(''{"status":"success", "message":"Registered Successfully!"}'');

EXCEPTION
    WHEN OTHERS THEN
        -- Catch any other unexpected database errors
        HTP.P(''{"status":"error", "message":"Server Error: ''||SQLERRM||''"}'');
END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'matchby_module',
      p_base_path      => '/matchby/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => 'Match By Drag 1 Progress API');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'matchby_module',
      p_pattern        => 'complete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Mark match-by activity as completed');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'matchby_module',
      p_pattern        => 'complete',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    -- Headers
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    UPDATE matchby_attempts
    SET
        score        = :score,
        attempted    = :attempted,
        status       = ''COMPLETED'',
        completed_at = SYSTIMESTAMP,
        updated_at   = SYSTIMESTAMP
    WHERE user_id     = TO_NUMBER(:user_id)
      AND activity_id = :activity_id;

    COMMIT;

    HTP.P(''{"status":"success","message":"Activity completed"}'');

EXCEPTION
    WHEN OTHERS THEN
        HTP.P(
            ''{"status":"error","message":"'' ||
            REPLACE(SQLERRM, ''"'', '''') ||
            ''"}''
        );
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'matchby_module',
      p_pattern        => 'progress',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Save or update match-by progress');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'matchby_module',
      p_pattern        => 'progress',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    -- Headers
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    MERGE INTO matchby_attempts t
    USING (
        SELECT
            TO_NUMBER(:user_id) AS src_user_id,
            :activity_id        AS src_activity_id
        FROM dual
    ) s
    ON (t.user_id = s.src_user_id AND t.activity_id = s.src_activity_id)
    WHEN MATCHED THEN
        UPDATE SET
            t.progress_json = :progress_json,
            t.score         = :score,
            t.attempted     = :attempted,
            t.status        = :status,
            t.updated_at    = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            user_id,
            activity_id,
            progress_json,
            score,
            attempted,
            status,
            started_at
        )
        VALUES (
            s.src_user_id,
            s.src_activity_id,
            :progress_json,
            :score,
            :attempted,
            :status,
            SYSTIMESTAMP
        );

    COMMIT;

    HTP.P(''{"status":"success","message":"Progress saved"}'');

EXCEPTION
    WHEN OTHERS THEN
        HTP.P(
            ''{"status":"error","message":"'' ||
            REPLACE(SQLERRM, ''"'', '''') ||
            ''"}''
        );
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'matchby_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Load saved match-by activity progress');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'matchby_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
DECLARE
    v_json   CLOB;
    v_status VARCHAR2(20);
    v_score  NUMBER;
BEGIN
    -- Headers
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    SELECT progress_json, status, score
    INTO v_json, v_status, v_score
    FROM matchby_attempts
    WHERE user_id     = TO_NUMBER(:user_id)
      AND activity_id = :activity_id;

    HTP.P(
        ''{ "status": "'' || v_status ||
        ''", "score": '' || NVL(v_score, 0) ||
        '', "data": '' || NVL(v_json, ''null'') || '' }''
    );

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        HTP.P(''{"status":"empty"}'');
    WHEN OTHERS THEN
        HTP.P(
            ''{"status":"error","message":"'' ||
            REPLACE(SQLERRM, ''"'', '''') ||
            ''"}''
        );
END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'mcq_api',
      p_base_path      => '/mcq/data/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'mcq_api',
      p_pattern        => 'questions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'mcq_api',
      p_pattern        => 'questions',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
      BEGIN
        INSERT INTO mcq_questions (activity_id, q_text, options)
        SELECT activity_id, question, answers
        FROM JSON_TABLE(:body, ''$.questions[*]''
          COLUMNS (
            activity_id NUMBER         PATH ''$.activity_id'',
            question    VARCHAR2(4000) PATH ''$.question'',
            answers     VARCHAR2(4000) PATH ''$.answers''
          )
        );
        :status := 201;
      END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'mcq_api',
      p_pattern        => 'questions',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
      SELECT 
        question_id AS "id",
        activity_id AS "activity_id",
        q_text       AS "question",
        options      AS "answers"
      FROM mcq_questions
      ORDER BY question_id DESC'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'mcq_api',
      p_pattern        => 'questions/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'mcq_api',
      p_pattern        => 'questions/:id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
      BEGIN
        UPDATE mcq_questions
        SET q_text  = :question,
            options = :answers
        WHERE question_id = :id;

        :status := 200;
      END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'mcq_module',
      p_base_path      => '/mcq/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'MCQ Progress 0 API');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'mcq_module',
      p_pattern        => 'complete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'mcq_module',
      p_pattern        => 'complete',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        BEGIN
            -- RESPONSE HEADERS
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            UPDATE mcq_attempts
            SET
                score = :score,
                attempted = :attempted,
                status = ''COMPLETED'',
                completed_at = SYSTIMESTAMP,
                updated_at = SYSTIMESTAMP
            WHERE user_id = :user_id
              AND activity_id = :activity_id;

            COMMIT;

            HTP.P(''{"status":"success","message":"MCQ completed"}'');

        EXCEPTION
            WHEN OTHERS THEN
                HTP.P(''{"status":"error","message":"Server error"}'');
        END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'mcq_module',
      p_pattern        => 'progress',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'mcq_module',
      p_pattern        => 'progress',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        BEGIN
            -- RESPONSE HEADERS
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            MERGE INTO mcq_attempts t
            USING (
                SELECT
                    :user_id     AS user_id,
                    :activity_id AS activity_id
                FROM dual
            ) s
            ON (t.user_id = s.user_id AND t.activity_id = s.activity_id)
            WHEN MATCHED THEN
                UPDATE SET
                    t.progress_json = :progress_json,
                    t.score = :score,
                    t.attempted = :attempted,
                    t.status = :status,
                    t.updated_at = SYSTIMESTAMP
            WHEN NOT MATCHED THEN
                INSERT (
                    user_id,
                    activity_id,
                    progress_json,
                    score,
                    attempted,
                    status,
                    started_at
                )
                VALUES (
                    :user_id,
                    :activity_id,
                    :progress_json,
                    :score,
                    :attempted,
                    :status,
                    SYSTIMESTAMP
                );

            COMMIT;

            HTP.P(''{"status":"success","message":"Progress saved"}'');

        EXCEPTION
            WHEN OTHERS THEN
                HTP.P(''{"status":"error","message":"Server error"}'');
        END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'mcq_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'mcq_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        DECLARE
            v_json CLOB;
        BEGIN
            -- RESPONSE HEADERS
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');

            -- ANTI-CACHING HEADERS: These force the browser to ask the server for fresh data
            -- instead of showing the "Summary" from a previous session.
            HTP.P(''Cache-Control: no-cache, no-store, must-revalidate'');
            HTP.P(''Pragma: no-cache'');
            HTP.P(''Expires: 0'');

            OWA_UTIL.HTTP_HEADER_CLOSE;

            -- SELECT DATA
            SELECT progress_json
            INTO v_json
            FROM mcq_attempts
            WHERE user_id = :user_id
              AND activity_id = :activity_id;

            -- OUTPUT JSON
            HTP.P(v_json);

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                -- If the row was deleted, we return this status so mcq.js starts fresh
                HTP.P(''{"status":"empty"}'');
            WHEN OTHERS THEN
                HTP.P(''{"status":"error","message":"Server error"}'');
        END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'private.api',
      p_base_path      => '/private/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'private.api',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'private.api',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM EMPLOYEES'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'profile_module',
      p_base_path      => '/profile/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'profile_module',
      p_pattern        => 'get',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'profile_module',
      p_pattern        => 'get',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT admin_id as "id", admin_name as "name", email as "email", role as "role" 
                             FROM lms_admins 
                             WHERE LOWER(email) = LOWER(:email)'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'profile_module',
      p_pattern        => 'update-name',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'profile_module',
      p_pattern        => 'update-name',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    UPDATE lms_admins 
       SET admin_name = :name 
     WHERE email = :email;

    IF SQL%ROWCOUNT > 0 THEN
        COMMIT;
        HTP.P(''{"status": "SUCCESS", "message": "User name updated successfully"}'');
    ELSE
        OWA_UTIL.status_line(nstatus => 404, creason => ''User Not Found'');
        HTP.P(''{"status": "ERROR", "message": "User not found"}'');
    END IF;
END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'profile_update_module',
      p_base_path      => '/profile-api/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'profile_update_module',
      p_pattern        => 'update',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'profile_update_module',
      p_pattern        => 'update',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    -- Targets user by the original email stored in your system
    UPDATE lms_admins 
       SET admin_name = :name, 
           email = :new_email 
     WHERE LOWER(email) = LOWER(:old_email);

    IF SQL%ROWCOUNT > 0 THEN
        COMMIT;
        HTP.P(''{"status": "SUCCESS", "message": "Profile updated"}'');
    ELSE
        OWA_UTIL.status_line(404);
        HTP.P(''{"status": "ERROR", "message": "Original user email not found"}'');
    END IF;
EXCEPTION WHEN OTHERS THEN
    OWA_UTIL.status_line(500);
    HTP.P(''{"status": "ERROR", "message": "'' || SQLERRM || ''"}'');
END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'sequence_module',
      p_base_path      => '/sequence/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => 'Sequence activity API');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sequence_module',
      p_pattern        => 'complete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Mark sequence activity as completed');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sequence_module',
      p_pattern        => 'complete',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    -- HEADERS
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    MERGE INTO sequence_attempts t
    USING (
        SELECT 
            TO_NUMBER(:user_id) AS src_user_id,
            :activity_id        AS src_act_id
        FROM dual
    ) s
    ON (t.user_id = s.src_user_id AND t.activity_id = s.src_act_id)
    WHEN MATCHED THEN
        UPDATE SET
            t.score        = :score,
            t.attempted    = :attempted,
            t.status       = ''COMPLETED'',
            t.completed_at = SYSTIMESTAMP,
            t.updated_at   = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            user_id,
            activity_id,
            score,
            attempted,
            status,
            started_at,
            completed_at
        )
        VALUES (
            s.src_user_id,
            s.src_act_id,
            :score,
            :attempted,
            ''COMPLETED'',
            SYSTIMESTAMP,
            SYSTIMESTAMP
        );

    COMMIT;

    HTP.P(''{"status":"success","message":"Activity completed"}'');

EXCEPTION
    WHEN OTHERS THEN
        HTP.P(
            ''{"status":"error","message":"'' ||
            REPLACE(SQLERRM, ''"'', '''') ||
            ''"}''
        );
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sequence_module',
      p_pattern        => 'progress',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Save sequence activity progress');
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sequence_module',
      p_pattern        => 'progress',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
BEGIN
    -- HEADERS
    OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
    HTP.P(''Access-Control-Allow-Origin: *'');
    OWA_UTIL.HTTP_HEADER_CLOSE;

    MERGE INTO sequence_attempts t
    USING (
        SELECT
            TO_NUMBER(:user_id) AS src_user_id,
            :activity_id        AS src_act_id
        FROM dual
    ) s
    ON (t.user_id = s.src_user_id AND t.activity_id = s.src_act_id)
    WHEN MATCHED THEN
        UPDATE SET
            t.progress_json = :progress_json,
            t.score         = :score,
            t.attempted     = :attempted,
            t.status        = :status,
            t.updated_at    = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            user_id,
            activity_id,
            progress_json,
            score,
            attempted,
            status,
            started_at
        )
        VALUES (
            s.src_user_id,
            s.src_act_id,
            :progress_json,
            :score,
            :attempted,
            :status,
            SYSTIMESTAMP
        );

    COMMIT;

    HTP.P(''{"status":"success","message":"Progress saved"}'');

EXCEPTION
    WHEN OTHERS THEN
        HTP.P(
            ''{"status":"error","message":"'' ||
            REPLACE(SQLERRM, ''"'', '''') ||
            ''"}''
        );
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sequence_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sequence_module',
      p_pattern        => 'progress/:user_id/:activity_id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        DECLARE
            v_final_json CLOB;
        BEGIN
            -- Headers
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            -- Fetch and Format
            SELECT JSON_OBJECT (
                       ''status'' VALUE status,
                       ''score''  VALUE NVL(score, 0),
                       ''data''   VALUE JSON_QUERY(progress_json, ''$'')
                   )
            INTO v_final_json
            FROM sequence_attempts
            WHERE user_id = TO_NUMBER(:user_id)
              AND activity_id = :activity_id;

            HTP.P(v_final_json);

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                :status := 404; -- This is the line causing the error
                HTP.P(''{"status":"empty", "message":"No data found"}'');
            WHEN OTHERS THEN
                :status := 500;
                HTP.P(''{"status":"error", "message":"'' || REPLACE(SQLERRM, ''"'', '''') || ''"}'');
        END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'session_mgmt_module',
      p_base_path      => '/exit_api/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Dedicated Logout and Session Management');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'session_mgmt_module',
      p_pattern        => 'logout',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'session_mgmt_module',
      p_pattern        => 'logout',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
        DECLARE
            -- Independent logging procedure
            PROCEDURE log_exit(p_email VARCHAR2, p_stat VARCHAR2) IS
                PRAGMA AUTONOMOUS_TRANSACTION;
            BEGIN
                INSERT INTO logout_history (user_email, status, logout_time)
                VALUES (p_email, p_stat, CURRENT_TIMESTAMP);
                COMMIT;
            EXCEPTION
                WHEN OTHERS THEN ROLLBACK;
            END;
        BEGIN
            -- CORS and JSON Headers
            OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
            HTP.P(''Access-Control-Allow-Origin: *'');
            HTP.P(''Access-Control-Allow-Headers: Content-Type'');
            HTP.P(''Access-Control-Allow-Methods: POST'');
            OWA_UTIL.HTTP_HEADER_CLOSE;

            -- Perform Logging
            log_exit(:email, ''SUCCESS'');

            -- Return Success JSON
            HTP.P(''{"status":"success", "message":"Logout recorded successfully"}'');

        EXCEPTION
            WHEN OTHERS THEN
                log_exit(:email, ''ERROR: '' || SUBSTR(SQLERRM, 1, 50));
                HTP.P(''{"status":"error", "message":"Logout processing failed"}'' );
        END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'simple_api',
      p_base_path      => '/simple/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Simple POST Test');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'simple_api',
      p_pattern        => 'test',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'simple_api',
      p_pattern        => 'test',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                               -- 1. Insert the data
                               INSERT INTO simple_post_test (user_name, content)
                               VALUES (:user_name, :content);

                               COMMIT;

                               -- 2. Return ONLY a simple JSON success message
                               OWA_UTIL.MIME_HEADER(''application/json'', TRUE);
                               HTP.P(''{"result": "Success"}''); 
                             END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'staff_management_api',
      p_base_path      => '/staff-api/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
                        l_new_id NUMBER;
                      BEGIN
                        INSERT INTO lms_staff (name, gender, email, mobile_number, role, status)
                        VALUES (:name, :gender, :email, :mobile_number, :role, :status)
                        RETURNING user_id INTO l_new_id;

                        COMMIT;

                        :status_code := 201;
                        HTP.P(''{"status": "Success", "message": "Staff created", "generated_id": '' || l_new_id || ''}'');
                      EXCEPTION
                        WHEN OTHERS THEN
                          :status_code := 400;
                          HTP.P(''{"status": "Error", "message": "'' || SQLERRM || ''"}'');
                      END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM lms_staff'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff/:id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                        UPDATE lms_staff SET 
                          name = :name, gender = :gender, email = :email, 
                          mobile_number = :mobile_number, role = :role, status = :status
                        WHERE user_id = :id;

                        IF SQL%ROWCOUNT > 0 THEN
                          HTP.P(''{"status": "Success", "message": "Staff record updated for ID: '' || :id || ''"}'');
                          :status_code := 200;
                        ELSE
                          HTP.P(''{"status": "Not Found", "message": "No staff found with ID: '' || :id || ''"}'');
                          :status_code := 404;
                        END IF;
                      END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff/:id',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                        DELETE FROM lms_staff WHERE user_id = :id;

                        IF SQL%ROWCOUNT > 0 THEN
                          HTP.P(''{"status": "Success", "message": "Staff record deleted"}'');
                          :status_code := 200;
                        ELSE
                          HTP.P(''{"status": "Not Found", "message": "Could not find staff with ID: '' || :id || ''"}'');
                          :status_code := 404;
                        END IF;
                      END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'staff_management_api',
      p_pattern        => 'staff/:id',
      p_method         => 'GET',
      p_source_type    => 'json/item',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM lms_staff WHERE user_id = :id'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'user',
      p_base_path      => '/user/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => 'User Analytics and Performance APIs');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'user',
      p_pattern        => 'analytics/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'user',
      p_pattern        => 'analytics/:id',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
WITH exercise_types AS (
    SELECT ''MCQ EXERCISES'' AS category_name, 13 AS total, ''MCQ'' AS type FROM dual
    UNION ALL
    SELECT ''MATCH EXERCISES'', 10, ''MATCH'' FROM dual
    UNION ALL
    SELECT ''SEQUENCE EXERCISES'', 3, ''SEQUENCE'' FROM dual
    UNION ALL 
    SELECT ''COMPLETEDWORD EXERCISE'', 3, ''COMPLETEDWORD'' FROM dual
),
raw_attempts AS (
    -- Gather all attempts first, safely converting IDs to numbers
    -- (Requires Oracle 12.2+. If on older version, remove "DEFAULT NULL ON CONVERSION ERROR")
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR) AS user_id, ''MCQ'' AS type, score 
    FROM mcq_attempts WHERE status = ''COMPLETED''
    UNION ALL
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR), ''MATCH'', score 
    FROM matchby_attempts WHERE status = ''COMPLETED''
    UNION ALL
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR), ''SEQUENCE'', score 
    FROM sequence_attempts WHERE status = ''COMPLETED''
    UNION ALL
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR), ''COMPLETEDWORD'', score 
    FROM COMPLETEDWORD_ATTEMPTS WHERE status = ''COMPLETED''
),
user_stats AS (
    SELECT user_id, type, COUNT(*) AS cnt, SUM(score) AS sum_score
    FROM raw_attempts
    WHERE user_id IS NOT NULL
    GROUP BY user_id, type
),
users_with_seq AS (
    SELECT u.*,
           ROW_NUMBER() OVER (ORDER BY TO_NUMBER(u.user_id DEFAULT NULL ON CONVERSION ERROR)) AS user_seq_id
    FROM lms_users u
    WHERE TO_NUMBER(u.user_id DEFAULT NULL ON CONVERSION ERROR) IS NOT NULL
)
SELECT
    e.category_name,
    NVL(s.cnt, 0) AS attempted,
    e.total,
    NVL(s.sum_score, 0) AS score,
    ROUND(NVL(s.cnt,0)/NULLIF(e.total,0)*100, 2) AS percentage,
    CASE
        WHEN ROUND(NVL(s.cnt,0)/NULLIF(e.total,0)*100, 2) < 40 THEN ''danger''
        WHEN ROUND(NVL(s.cnt,0)/NULLIF(e.total,0)*100, 2) BETWEEN 40 AND 70 THEN ''warning''
        ELSE ''success''
    END AS theme_color
FROM users_with_seq u
CROSS JOIN exercise_types e
LEFT JOIN user_stats s
    ON s.user_id = TO_NUMBER(u.user_id)
   AND s.type = e.type
WHERE u.user_seq_id = :id
'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'user',
      p_pattern        => 'performance',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'user',
      p_pattern        => 'performance',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'WITH all_completions AS (
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR) AS user_id FROM mcq_attempts WHERE status = ''COMPLETED''
    UNION ALL
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR) FROM sequence_attempts WHERE status = ''COMPLETED''
    UNION ALL
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR) FROM matchby_attempts WHERE status = ''COMPLETED''
    UNION ALL
    SELECT TO_NUMBER(user_id DEFAULT NULL ON CONVERSION ERROR) FROM completedword_attempts WHERE status = ''COMPLETED''
),
user_totals AS (
    SELECT user_id, COUNT(*) AS completed_count
    FROM all_completions
    WHERE user_id IS NOT NULL
    GROUP BY user_id
)
SELECT
    ROW_NUMBER() OVER (ORDER BY TO_NUMBER(u.user_id DEFAULT NULL ON CONVERSION ERROR)) AS user_seq_id,

    -- 🟢 FIX: Stitching the new first and last name columns together 
    TRIM(u.c_first_name || '' '' || u.c_last_name) AS user_name,

    u.email,
    NVL(ut.completed_count, 0) AS attempted_exercise,
    29 AS total_exercise
FROM lms_users u
LEFT JOIN user_totals ut
    ON ut.user_id = TO_NUMBER(u.user_id DEFAULT NULL ON CONVERSION ERROR)
WHERE TO_NUMBER(u.user_id DEFAULT NULL ON CONVERSION ERROR) IS NOT NULL
ORDER BY TO_NUMBER(u.user_id DEFAULT NULL ON CONVERSION ERROR)'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'user',
      p_pattern        => 'registration-count',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'user',
      p_pattern        => 'registration-count',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
      WITH total_user_activity AS (
          SELECT CAST(user_id AS VARCHAR2(50)) AS user_id, activity_id
          FROM api_dev_user.mcq_attempts
          UNION ALL
          SELECT CAST(user_id AS VARCHAR2(50)), activity_id
          FROM api_dev_user.sequence_attempts
          UNION ALL
          SELECT CAST(user_id AS VARCHAR2(50)), activity_id
          FROM api_dev_user.matchby_attempts
      ),
      user_counts AS (
          SELECT user_id, COUNT(DISTINCT activity_id) AS exercise_count
          FROM total_user_activity
          GROUP BY user_id
      )
      SELECT
          COUNT(l.user_id) AS registrationcount,
          COUNT(CASE WHEN NVL(u.exercise_count, 0) BETWEEN 0 AND 30 THEN 1 END) AS easycount,
          COUNT(CASE WHEN u.exercise_count BETWEEN 31 AND 60 THEN 1 END) AS intermediatecount,
          COUNT(CASE WHEN u.exercise_count BETWEEN 61 AND 90 THEN 1 END) AS hardcount
      FROM api_dev_user.lms_users l
      LEFT JOIN user_counts u
             ON CAST(l.user_id AS VARCHAR2(50)) = u.user_id'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'user_update_module',
      p_base_path      => '/user-api/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'user_update_module',
      p_pattern        => 'profile',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'user_update_module',
      p_pattern        => 'profile',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
  BEGIN
      UPDATE lms_admins 
         SET admin_name = :name, 
             email      = :new_email,
             mobile     = :mobile -- ✅ Mobile field added
       WHERE LOWER(email) = LOWER(:old_email);

      IF SQL%ROWCOUNT > 0 THEN
          COMMIT;
          HTP.P(''{"status": "SUCCESS", "message": "Profile updated successfully"}'');
      ELSE
          OWA_UTIL.status_line(404);
          HTP.P(''{"status": "ERROR", "message": "Original user record not found"}'');
      END IF;
  EXCEPTION WHEN OTHERS THEN
      OWA_UTIL.status_line(500);
      HTP.P(''{"status": "ERROR", "message": "'' || SQLERRM || ''"}'');
  END;'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'v1.konzeptes',
      p_base_path      => '/v1/konzeptes/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'config',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'config',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT 
                           json_arrayagg(
                             json_object(
                               ''id''        VALUE ID,
                               ''label''     VALUE LABEL,
                               ''smLabel''   VALUE SM_LABEL
                             ) ORDER BY CREATED_AT ASC
                             RETURNING CLOB
                           ) as "list"
                        FROM CURRICULUM_CARDS'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'get-icon/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'get-icon/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT mime_type, image_blob 
                             FROM CURRICULUM_CARDS 
                             WHERE IMG = REPLACE(:id, ''.png'', '''')'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'image/bg/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'image/bg/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT NVL(bg_mime_type, ''image/png''), bg_image_blob 
                         FROM CURRICULUM_CARDS WHERE ID = :id'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'image/icon/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'image/icon/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT NVL(mime_type, ''image/png''), image_blob 
                         FROM CURRICULUM_CARDS WHERE ID = :id'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'manage-card',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'manage-card',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
    DECLARE
        v_id_raw   VARCHAR2(50)   := :id;
        v_label    NVARCHAR2(500) := :label;
        v_sm       VARCHAR2(255)  := :smLabel;
        v_id_num   NUMBER;
        v_out_id   NUMBER;
        l_response CLOB;
    BEGIN
        -- Safe Number Conversion
        IF v_id_raw IS NOT NULL AND REGEXP_LIKE(v_id_raw, ''^[0-9]+$'') THEN
            v_id_num := TO_NUMBER(v_id_raw);
        ELSE
            v_id_num := NULL;
        END IF;

        -- UPDATE or INSERT
        IF v_id_num IS NOT NULL AND v_id_num > 0 THEN
            UPDATE CURRICULUM_CARDS
            SET LABEL = v_label, SM_LABEL = v_sm
            WHERE ID = v_id_num
            RETURNING ID INTO v_out_id;
        ELSE
            INSERT INTO CURRICULUM_CARDS (LABEL, SM_LABEL, MIME_TYPE, IMAGE_BLOB, BG_IMAGE_BLOB)
            VALUES (v_label, v_sm, ''image/png'', EMPTY_BLOB(), EMPTY_BLOB())
            RETURNING ID INTO v_out_id;
        END IF;

        -- FORCE JSON RESPONSE
        l_response := ''{"id": '' || v_out_id || '', "status": "success"}'';

        OWA_UTIL.MIME_HEADER(''application/json'', FALSE);
        HTP.P(''Content-Length: '' || DBMS_LOB.GETLENGTH(l_response));
        OWA_UTIL.HTTP_HEADER_CLOSE;
        HTP.P(l_response);

        :status := 200;
    EXCEPTION WHEN OTHERS THEN
        :status := 400; 
    END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'manage-card',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN DELETE FROM CURRICULUM_CARDS WHERE ID = :id; :status := 204; END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'upload-icon/:slug',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'upload-icon/:slug',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                               UPDATE CURRICULUM_CARDS
                               SET image_blob = :body, mime_type = :content_type
                               WHERE IMG = :slug;
                               :status := 200;
                             END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'upload/bg/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'upload/bg/:id',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                               UPDATE CURRICULUM_CARDS
                               SET bg_image_blob = :body, bg_mime_type = :content_type
                               WHERE ID = :id;
                               :status := 200;
                             END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'upload/icon/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'v1.konzeptes',
      p_pattern        => 'upload/icon/:id',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
                               UPDATE CURRICULUM_CARDS
                               SET image_blob = :body, mime_type = :content_type
                               WHERE ID = :id;
                               :status := 200;
                             END;'
      );


  COMMIT; 
END;